version: "3.9"
services:
  ros2container1:
    image: ros_test_env
    volumes:
      - ./scripts:/scripts
    entrypoint: /scripts/rosnode1.bash
    networks:
      test_network:
        ipv4_address: 10.0.0.2

  ros2container2:
    image: ros_test_env
    volumes:
      - ./scripts:/scripts
    networks:
      test_network:
        ipv4_address: 10.0.0.3
  ros2container3:
    image: ros_test_env
    volumes:
      - ./scripts:/scripts
    networks:
      test_network:
        ipv4_address: 10.0.0.4

networks:
  test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

